v_1.0 just phone number verifi
vita-olshevska/personal_assistant_cli pull request #1
Opened 2021-08-27 14:35 UTC by IhorKomkov

2021-08-27 14:53 UTC, vita-olshevska requested changes

2021-08-27 14:53 UTC, vita-olshevska commented on verifi.py
> +# тут написаны функции верификации телефонных номеров и email
Файл ніяк не пов'язаний із запропонованою структурою проекта. Файл не може знаходитися в корні проекту. 
Пропоную тимчасово перенести його в comon і використати його в імплементації AddressBook.

2021-08-27 14:53 UTC, vita-olshevska commented on verifi.py
> +def phone_vrifi(phone_num):
мовна помилка: verify

2021-08-27 14:53 UTC, vita-olshevska commented on verifi.py
> +                return verifi_phone_num
Можливо для зручності використання краще повертати 2 результати: телефон у форматованому вигляді та текст помилки, якщо вона є.
Наприклад, phone_verify("+380939998877") -> ("+380939998877", None)
                    phone_verify("asdasdsada") -> (None, "Error: ...")

2021-08-27 14:57 UTC, IhorKomkov commented on verifi.py
> +                return verifi_phone_num
добре, принято дороблю)

2021-08-28 10:12 UTC, vita-olshevska commented on core/common/verifi.py
> +def phone_verifi(phone_num):
Помилка в англійській назві, потрібно verify замість verifi. І те ж саме в назві файлу.

2021-08-28 10:26 UTC, vita-olshevska commented on core/common/verifi.py
> +            return (None, 'Количество цифр в ведённом номере не \
Повідомлення про помилку (другий елемент кортежу) треба зробити англійською.

2021-08-28 10:32 UTC, vita-olshevska commented on core/common/verifi.py
> +# примеры нломеров в списке
Для фінального варіанту закоментований текст треба прибрати. Можна залишити лише опис функцій.

2021-08-28 10:35 UTC, vita-olshevska commented on core/common/verifi.py
> +    print(phone_verifi(i))
Перевірки тут теж не має бути, лише самі функції. Інакше при зверненні до цього файлу ці перевірки теж запустяться, а нам таке не треба.

2021-08-28 10:40 UTC, vita-olshevska requested changes
Прибрати закоментований текст та додаткові перевірки, які не відносяться до тіла функцій, зробити вивід тексту англійською. Виправити помилки.

2021-08-28 10:51 UTC, IhorKomkov commented on core/common/verifi.py
> +def phone_verifi(phone_num):
Готово)

2021-08-28 10:51 UTC, IhorKomkov commented on core/common/verifi.py
> +            return (None, 'Количество цифр в ведённом номере не \
Вже зробив, просто ще не коммітив)

2021-08-28 10:52 UTC, IhorKomkov commented on core/common/verifi.py
> +# примеры нломеров в списке
Для фінального варіанту приберу)

2021-08-28 10:52 UTC, IhorKomkov commented on core/common/verifi.py
> +    print(phone_verifi(i))
Так само для фінального варіанту буде прибрано)

2021-08-29 19:26 UTC, vita-olshevska commented on core/common/verify.py
> +# тут написаны функции верификации телефонных номеров и email
Все добре, видаляй зайве та відправляй фіналку.

2021-08-29 19:28 UTC, vita-olshevska requested changes
Все добре, видаляй зайве та відправляй фіналку.

2021-08-29 19:36 UTC, vita-olshevska approved these changes

2021-08-29 19:36 UTC, merged