Tasks 02 04 06 07 08 09 10 11
vita-olshevska/personal_assistant_cli pull request #4
Opened 2021-08-28 14:59 UTC by SageSage888

2021-08-28 22:13 UTC, vita-olshevska commented on core/note_book/note_book.py
> +            print("Something went wrong", error)
Метод має повертати повідомлення типу str у будь-якому випадку (успіх або помилка).

2021-08-28 22:16 UTC, vita-olshevska commented on core/note_book/note_book.py
> +    def add(self, note: str, name: str):
Домовилися, що цей метод без аргументу name. В цьому методі на віх буде лише замітка.

2021-08-28 22:29 UTC, vita-olshevska commented on core/note_book/note_book.py
> +            print("Something went wrong", error)
Ти у всіх методах не маєш робити цей print. Опис помилки треба повернути (return) як стрічку (типу str). Якщо помилки немає, то повертаєш всерівно стрічку, в якій буде повідомлення, наприклад, "Change is succesfull." І так для кожного із шести основниз методів для NoteBook.

2021-08-28 22:35 UTC, vita-olshevska commented on core/common/db_config.py
> +# cur.execute("""INSERT INTO contacts(id, name, phone, email, birthday)
Потрібно прибрати всі зайві коментарі. Залишити можна лише опис.

2021-08-28 22:37 UTC, vita-olshevska commented on core/address_book/address_book.py
> +    def add(self, name, phone: int, address, email, birthday):
Є певні зміни для аргументів функції, треба обговорити особисто.

2021-08-28 22:39 UTC, vita-olshevska commented on core/address_book/address_book.py
> +import core.common.db_config as db
У всіх методах потрібно повернути стрічку, а не робити print. Ця стрічка - це або опис помилки, або повідомлення про успіх.

2021-08-28 22:40 UTC, vita-olshevska requested changes
У всіх основних методах NoteBook та AddressBook замість print має бути return певної стрічки. Ця стрічка, це або опис помилки (типу str). Або якщо помилки немає, то в цій стрічці  має бути повідомлення про успіх, наприклад, "Change is succesfull."

2021-08-29 08:51 UTC, SageSage888 commented on core/note_book/note_book.py
> +    def add(self, note: str, name: str):
done

2021-08-29 12:58 UTC, vita-olshevska commented on core/address_book/address_book.py
> +        update_note = (arg[fields[1]], arg[fields[0]])
В словнику не обо'язково перший ключ буде саме им'я. Раджу використовувати прямий доступ: arg["name"]

2021-08-29 13:21 UTC, vita-olshevska commented on core/address_book/address_book.py
> +        elif fields[1] == 'phone':
Замість перевірки аргументів (if / elif всіх), можно напряму редагувати sql запит за ключом наступним чином:
for key in arg.keys():
   if key != "name":
       update_note = (arg[key], arg["name"])
       sql = f"""UPDATE contacts
                     SET {key} = ?
                     WHERE name = ?"""

2021-08-29 13:22 UTC, vita-olshevska approved these changes

2021-08-29 13:22 UTC, merged