Dima's branch
vita-olshevska/personal_assistant_cli pull request #8
Opened 2021-08-29 21:21 UTC by SageSage888

please check

2021-08-29 22:37 UTC, vita-olshevska commented on core/address_book/address_book.py
>              print("Something went wrong", error)
Цей результат треба повернути, а не вивести. (return, а не print)

2021-08-29 22:41 UTC, vita-olshevska commented on core/address_book/address_book.py
>              print("Something went wrong", error)
У випадку помилки ми отримаємо водночас і повідомлення про помилку, і повідомлення про успішну операцію.

Треба return, а не print.

2021-08-29 22:44 UTC, vita-olshevska commented on core/note_book/note_book.py
> +                print(' id ', ' tag ', ' note ')
Заголовок потрібно додати на початок у стрічку, яка потім вертається через return.

2021-08-29 22:45 UTC, vita-olshevska commented on core/note_book/note_book.py
>              for i in db.cur.fetchall():
Стрічки потрібно склеїти через join, а не вивести у циклі. А потім цю склейку повернути як результат.

2021-08-29 22:48 UTC, vita-olshevska requested changes
Замінити print на return належним чином.

2021-08-30 08:06 UTC, SageSage888 commented on core/address_book/address_book.py
>              print("Something went wrong", error)
done

2021-08-30 08:07 UTC, SageSage888 commented on core/address_book/address_book.py
>              print("Something went wrong", error)
done

2021-08-30 08:11 UTC, SageSage888 commented on core/note_book/note_book.py
> +                print(' id ', ' tag ', ' note ')
done

2021-08-30 08:15 UTC, SageSage888 commented on core/note_book/note_book.py
>              for i in db.cur.fetchall():
там цикл для db.cur.fetchall(), он много где так работает. Сделал через result, который потом возвращаю (не принчу)

2021-08-30 10:43 UTC, vita-olshevska approved these changes

2021-08-30 10:46 UTC, merged